- shn/CUSA07211-01.01.shn
Removes space in title to not mess up sorting by name
> Remove space in title

- json/CUSA07211_01.00.json
- json/CUSA07211_01.01.json
These cheats only work for the base game on 1.00 not 1.01
> Update and rename CUSA07211_01.01.json to CUSA07211_01.00.json

- json/CUSA16745_01.00.json
Added CUSA16745_01.00.json by copying CUSA16745_01.01.json and changing the version. Successfully tested the first three options with CUSA16745 v1.00 so I assume other offsets are correct too.
> Added CUSA16745_01.00.json

- json/CUSA25283_01.02.json
Added cheats for CUSA25283 "My Name is Mayo 2". Urgently needed as saving is broken in the only version I manage to find in the wild world web.
> Added CUSA25283_01.02.json

- shn/CUSA01760_01.02.shn
Includes godmode + 1 hit kill and max souls on gain
> Add Dark souls 2 CUSA01760 Update v01.02 shn

- shn/CUSA02290_01.33.shn
Only includes godmode for the zombies mode. so far tested on 3 different maps and confirmed working
> Add Black ops 3 CUSA02290 V01.33 trainer (SHN)

- shn/CUSA32167_01.03.shn
Re-adds and fixes the 1 Hit Kill and adds a better description.
> Update (No More Heroes III) (CUSA32167) (01.03) SHN

- mc4/CUSA02299_01.19.mc4.xml
- mc4/CUSA02431_01.03.mc4.xml
- mc4/CUSA23766_01.10.mc4.xml
- shn/CUSA00309_01.07.shn
- shn/CUSA44317_01.01.shn
> Blasphemous_II_CUSA44317_01.01

- shn/CUSA06314_01.01.shn
- shn/CUSA34029_01.33_sp23-cod.elf.shn
> Call_of_Duty_Modern_Warfare_III

- shn/CUSA34384_05.01.json
- shn/CUSA34384_05.01.shn
- shn/CUSA34386_05.01.json
- shn/CUSA34386_05.01.shn
- shn/CUSA34388_05.01.json
- shn/CUSA34388_05.01.shn
- shn/CUSA34390_05.01.json
- shn/CUSA34390_05.01.shn
- shn/CUSA34392_05.01.json
- shn/CUSA34392_05.01.shn
- shn/CUSA34394_05.01.json
- shn/CUSA34394_05.01.shn
Tested and works well. Please merge :-)
oops, just af4cbdb lol
> GOW Ragnarok 5.01 latest revision

- CUSA34384_05.04.json
- CUSA34386_05.04.json
- CUSA34388_05.04.json
- CUSA34390_05.04.json
- CUSA34392_05.04.json
- CUSA34394_05.04.json
- json/CUSA34384_05.04.json
- json/CUSA34386_05.04.json
- json/CUSA34388_05.04.json
- json/CUSA34390_05.04.json
- json/CUSA34392_05.04.json
- json/CUSA34394_05.04.json
> Tiny correction of Ragnarok 5.04 JSONs internal version number

- shn/CUSA04607_01.02.shn
- shn/CUSA10908_01.05.shn
- shn/CUSA17776_01.14.shn
- shn/CUSA20133_01.12.shn
Marvels_Spider-Man_Miles_Morales_CUSA17776_01.14
> My_Time_at_Portia_CUSA10908_01.05

- json/CUSA34384_05.05.json
- json/CUSA34386_05.05.json
- json/CUSA34388_05.05.json
- json/CUSA34390_05.05.json
- json/CUSA34392_05.05.json
- json/CUSA34394_05.05.json
God of War Ragnarok (+Valhalla DLC compatibility)
> Pharaoh2k latest cheats

- json/CUSA05725_04.00.json
- shn/CUSA05725_04.00.shn
Tested, works great and no conflicts. :)
Please merge.
Thanks
> Pharaoh2k Witcher 4.0 trainers

- json/CUSA32132_01.13.json
- json/CUSA32137_01.13.json
- shn/CUSA32132_01.13.shn
- shn/CUSA32137_01.13.shn
Tested and working well. No conflicts.
Please merge.
Thanks :-)
> Like a Dragon Infinite Wealth 01.13 trainers

- shn/CUSA32132_01.13_2.shn
- shn/CUSA32137_01.13_2.shn
> Like A Dragon Infinite Wealth

- json/CUSA32132_01.13.json
- json/CUSA32137_01.13.json
- shn/CUSA32132_01.13.shn
- shn/CUSA32137_01.13.shn
Tested and working perfectly. No conflicts.
Please merge.
Thank you :)
> Like a Dragon Infinite Wealth latest revisions (public release)

- json/CUSA36581_01.04.json
- json/CUSA36582_01.04.json
- shn/CUSA36581_01.04.shn
- shn/CUSA36582_01.04.shn
Trainers tested and are working perfectly. No conflicts.
Please merge. :)
Thank you!
> Prince of Persia The Lost Crown

- json/CUSA36581_01.04.json
- json/CUSA36582_01.04.json
- shn/CUSA36581_01.04.shn
- shn/CUSA36582_01.04.shn
Tested and working perfectly. No conflicts.
Please merge.
Thanks :)
> Update for my lost crown trainers

- shn/SCUS94228_01.00.shn
- shn/SCUS94402_01.00.shn
- shn/SCUS94467_01.00.shn
- shn/SLES00608_01.00.shn
- shn/SLES01064_01.00.shn
- shn/SLES03986_01.00.shn
- shn/SLES04123_01.00.shn
- shn/SLES04155_01.00.shn
- shn/SLPS00950_01.00.shn
- shn/SLPS03354_01.00.shn
- shn/SLUS00288_01.00.shn
- shn/SLUS00748_01.00.shn
- shn/SLUS00756_01.00.shn
> Ali-mk  ps1 trainers

- shn/CUSA16221_01.09.shn
- shn/CUSA27043_01.09.shn
- shn/CUSA36846_01.27.shn
- shn/CUSA36986_01.27.shn
- shn/CUSA40651_01.10.shn
- shn/CUSA40652_01.10.shn
> Streets Of Rage 4

- shn/CUSA07104_01.01.shn
- shn/CUSA42378_01.04.shn
Game="Resident Evil - Code - Veronica X" Moder="Ali-mk" Game="Contra.Operation.Galuga" Moder="Ali-mk"
> Resident Evil - Code - Veronica X

- json/CUSA34118_16.01.json
- json/CUSA34119_16.01.json
- json/CUSA34120_16.01.json
- json/CUSA34121_16.01.json
- json/CUSA40262_16.01.json
- shn/CUSA34118_16.01.shn
- shn/CUSA34120_16.01.shn
- shn/CUSA34121_16.01.shn
- shn/CUSA40262_16.01.shn
A nice trainer by d01v.
Please merge.
Thanks :-)
> Monster hunter rise sunbreak v16.01 trainers

- shn/CUSA15280_01.22_default.elf.shn
- shn/CUSA17624_01.02.shn
- shn/CUSA18581_01.18.shn
- shn/CUSA18723_01.18.shn
- shn/CUSA20499_01.05.shn
- shn/CUSA26370_01.03.shn
- shn/CUSA28527_01.18.shn
- shn/CUSA28863_01.18.shn
- shn/CUSA45205_01.02.shn
- shn/SLUS00974_01.00.shn
- shn/SLUS01270_01.00.shn
Game="Call Of Duty Modern Warfare" Moder="Celogamez" Cusa="CUSA15280" Game="infinite-Beyond-the-mind" Moder="Ali-mk" Cusa="CUSA17624" Game="Cuphead" Moder="Celogamez" Cusa="CUSA20499"
Game="New Joe and Mac Caveman Ninja" Moder="Ali-mk" Cusa="CUSA26370" Version="01.03 Game="Teenage Mutant Ninja Turtles Arcade Wrath of The Mutants" Moder="Ali-mk" Cusa="CUSA45205" Version="01.02 Game="Medal of Honor" Moder="Ali-mk" Cusa="SLUS00974" Version="01.00" Game="Medal of Honor  Underground" Moder="Ali-mk" Cusa="SLUS01270" Version="01.00"
> New Cheats

- json/CUSA02290_01.33.json
the one Skal upload didnt have inf ammo
> Black Ops 3 Update

- json/CUSA06027_15.21.json
- json/CUSA07708_15.21.json
- json/CUSA07713_15.21.json
- json/CUSA09554_15.21.json
- shn/CUSA06027_15.21.shn
- shn/CUSA07708_15.21.shn
- shn/CUSA07713_15.21.shn
- shn/CUSA09554_15.21.shn
Trainers have been well-tested.
Please kindly merge
Thanks :-)
> Monster Hunter World v15.21 (all regions) by d01v

- json/CUSA19500_01.03_LTCG-BioGame.elf.json
- shn/CUSA19500_01.03_LTCG-BioGame.elf.shn
- shn/CUSA19515_01.03_LTCG-BioGame.elf.shn
2 issues caused by incorrect porting of my Shnext to SHN/JSON in Mass Effect 1 have been corrected.
Hopefully no more porting issues...
Thank you :-)
> Mass Effect Legendary Edition Trilogy  fixes

- json/CUSA00265_01.95.json
> Add more cheats -> CUSA00265_01.95.json

- json/CUSA00265_01.95.json
Cheat: "Freeze Potions"
Freezes the effect duration
Also a side effect of Poison not doing any damage to you
> Add 1 cheat to CUSA00265_01.95.json

- shn/CUSA18653_01.07.shn
- shn/CUSA34370_01.08.shn
- shn/CUSA36581_01.40_2.shn
- shn/CUSA36582_01.40_2.shn
- shn/CUSA36583_01.40_2.shn
- shn/CUSA40641_01.10.shn
- shn/CUSA40651_01.10.shn
- shn/CUSA40653_01.10.shn
- shn/CUSA42502_01.01.shn
> Game="Star Ocean The Second Story R" Moder="Celogamez"

- json/CUSA18581_01.21.json
- json/CUSA18723_01.21.json
- json/CUSA28527_01.21.json
- json/CUSA28863_01.21.json
- shn/CUSA18581_01.21.shn
- shn/CUSA18723_01.21.shn
- shn/CUSA28527_01.21.shn
- shn/CUSA28863_01.21.shn
Please kindly upload. No conflicts.
Thank you :-)
> Elden Ring v01.21 trainers (all regions)

- json/CUSA12771_01.05.json
- json/CUSA12824_01.05.json
- json/CUSA18581_01.21.json
- json/CUSA18723_01.21.json
- json/CUSA28527_01.21.json
- json/CUSA28863_01.21.json
- shn/CUSA12771_01.05.shn
- shn/CUSA12824_01.05.shn
- shn/CUSA18581_01.21.shn
- shn/CUSA18723_01.21.shn
- shn/CUSA28527_01.21.shn
- shn/CUSA28863_01.21.shn
Tested and working well.
No conflicts.
Thank you! :-)
> Elden Ring 1.21 and Hogwarts Legacy 1.05 

- json/CUSA23631_01.02.json
- json/CUSA33778_01.03.json
- json/CUSA47037_01.02.json
- json/CUSA47038_01.02.json
- shn/CUSA23631_01.02.shn
- shn/CUSA33778_01.03.shn
- shn/CUSA47037_01.02.shn
- shn/CUSA47038_01.02.shn
Works well.
No conflicts.
Thank you! :-)
> Star Wars Jedi Survivor v01.03

- json/CUSA23631_01.02.json
- json/CUSA47037_01.02.json
- json/CUSA47038_01.02.json
- shn/CUSA23631_01.02.shn
- shn/CUSA47037_01.02.shn
- shn/CUSA47038_01.02.shn
A minor bug fix for GoldHEN menu compatibility.
Thank you! :-)
> Metaphor ReFantazio v01.02 GH compatibility bugfix

- json/CUSA23631_01.03.json
- json/CUSA47037_01.03.json
- json/CUSA47038_01.03.json
- shn/CUSA23631_01.03.shn
- shn/CUSA47037_01.03.shn
- shn/CUSA47038_01.03.shn
Metaphor ReFantazio v01.03 by d01v, all regions
No conflicts.
Thank you! :-)
> Metaphor ReFantazio v01.03 by d01v

- json/CUSA05571_04.06.json
- json/CUSA05572_04.06.json
- json/CUSA05573_04.06.json
- json/CUSA05574_04.06.json
- json/CUSA05644_04.06.json
- shn/CUSA05571_04.06.shn
- shn/CUSA05572_04.06.shn
- shn/CUSA05573_04.06.shn
- shn/CUSA05574_04.06.shn
- shn/CUSA05644_04.06.shn
Trainers have been tested and work well.
Thank you & Happy New Year! :-)
> The Witcher 3 Wild Hunt v04.06 - all regions

- json/CUSA05049_01.06.json
- json/CUSA11758_01.00.json
- json/CUSA14936_01.03.json
- json/CUSA17195_01.06.json
- json/CUSA17774_01.05.json
- json/CUSA19412_01.05.json
- json/CUSA32236_01.08.json
- json/CUSA35761_01.08.json
- json/CUSA41744_01.01.json
CUSA41744_01.01"Talixme"
CUSA17195_01.06"Talixme"
CUSA32236_01.08"Talixme"
CUSA17774_01.05"Talixme"
CUSA14936_01.03"Talixme"
> cheat update

- json/CUSA05987_01.09.json
- json/CUSA26258_01.01.json
- shn/CUSA27816_01.02.shn
- shn/CUSA34766_01.31.shn
- shn/CUSA42722_01.02.shn
DEATHS GAMBIT    "credits": Talixme
> DEATHS GAMBIT    "credits": Talixme

- json/CUSA08829_01.67.json
- shn/CUSA00324_01.05.shn
- shn/CUSA44067_01.02.shn
Game="MERCENARY-KINGS" Moder="Ali-mk
> Game="MERCENARY-KINGS" Moder="Ali-mk

- CUSA02353_01.05.shn
- CUSA07953_01.60_3.shn
- CUSA32946_01.00.shn
Game="Salt and Sanctuary" Moder="Ali-mk
Game="Final Vendetta" Moder="Ali-mk
Game="Bloodstained Ritual of the Night" Moder="Bandicootmonito
> Salt and Sanctuary" Moder="Ali-mk

- shn/CUSA42936_01.09.shn
- shn/CUSA50688_01.02.shn
Game="Double Dragon Gaiden" Moder="Ali-mk"
> Game="Nine Sols" Moder="Ali-mk"

- json/CUSA48853_01.02.json
- json/CUSA50614_01.02.json
- json/CUSA50615_01.02.json
- json/CUSA50617_01.02.json
- shn/CUSA48853_01.02.shn
- shn/CUSA50614_01.02.shn
- shn/CUSA50615_01.02.shn
- shn/CUSA50617_01.02.shn
Fully tested and works fine.
Thank you :-)
> Elden Ring Nightreign v01.02 - All regions

- json/CUSA09435_01.12.json
For the v1.12 update of the game, from the moder "Talixme". Tested
> GAME="Trials Rising(TM)" for 1.12 version

- shn/CUSA49799_01.01.shn
- shn/CUSA49865_01.03.shn
Game="The Thing Remastered" Moder="Ali-mk"
> Game="Onimusha 2 Samurais Destiny" Moder="Ali-mk"

- json/CUSA39420_01.02
From 2pt, convert on .json format...
> Hollow Knight Silksong v01.02

- json/CUSA01154_01.16.json
- shn/CUSA41097_01.21.shn
Metal Gear Solid V: The Phantom Pain   "credits  "Sondio"
> Metal Gear Solid V: The Phantom Pain

- json/CUSA26615_01.07.json
From Bandicootmonito, json by Chronoss
> Grand Theft Auto Vice City: The Definitive Edition

- shn/CUSA32836_01.50.shn
Game="Naruto x Boruto Ultimate Ninja Storm Connections Ultimate Edition" Moder="Bandicootmonito
> Naruto x Boruto Ultimate Ninja Storm
